
FROM node:22-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy app files
COPY . .

# Expose port and start dev server
EXPOSE 3000
CMD ["npm", "run", "dev"]
