services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3010:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

volumes:
  db:
    driver: local
